#if we are not logged in don't load all the extra stuff - helps with scp and rsync
if [ -z "$PS1" ]; then
  return;
fi

#load in all our nice stuff
if [[ -f $HOME/.bash_profile ]]; then
  source $HOME/.bash_profile
fi
